# Generated by Django 4.0.5 on 2024-04-17 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_title', models.CharField(max_length=255)),
                ('book_rating', models.FloatField()),
                ('published_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
