# Generated by Django 4.0.5 on 2024-04-18 12:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('books', '0004_alter_books_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='books',
            name='users',
        ),
        migrations.AddField(
            model_name='books',
            name='users',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='books', to=settings.AUTH_USER_MODEL),
        ),
    ]
