# Generated by Django 4.0.5 on 2024-04-22 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_rename_books_book'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='book_rating',
            new_name='rating',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='book_title',
            new_name='title',
        ),
        migrations.AddField(
            model_name='book',
            name='author',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='book',
            name='genre',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='book',
            name='review',
            field=models.TextField(default=''),
        ),
    ]
